# Generated by Django 5.2.4 on 2025-07-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.CharField(blank=True, help_text='Lenguajes utilizados en el proyecto, separados por coma.', max_length=150),
        ),
    ]
